version: 2.1

orbs:
  slack: circleci/slack@2.2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
      # Restore dependencies from the cache.
          keys:
          # Only install dependencies when the checksum of the package.json changes.
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found.
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run build
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          # Persist the previous steps to the workspace.
          root: ~/repo
          paths: .

  create-v5-v6-branch:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:zvnLkEEwEXtFhURIUaOfuiwK71PxzXr79w9CIogoEew"
      - run:
          name: "Create v5 and v6 branch"
          command: |
            echo $CIRCLE_BRANCH
            # Store the name of the current branch
            CURRENT_BRANCH=${CIRCLE_BRANCH}

            echo "CURRENT_BRANCH=${CIRCLE_BRANCH}" > current_branch.txt
            
            echo "Function to create or checkout a branch"
            create_or_checkout_branch() {
                # First param is BRANCH_NAME
                BRANCH_NAME=$1
                # Check if the branch exists
                if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
                    # Checkout if it exists
                    echo "Branch $BRANCH_NAME already exists, checking out to $CURRENT_BRANCH."
                    git checkout $CURRENT_BRANCH
                else
                    # Create and push branch if it doesn't exist
                    echo "Creating new branch $BRANCH_NAME."
                    git checkout -b $BRANCH_NAME

                    git push origin $BRANCH_NAME
                    echo "Branch $BRANCH_NAME pushed to remote, checking out to $CURRENT_BRANCH."

                    git checkout $CURRENT_BRANCH
                fi
            }     

            echo "Create and push -v5 branch"
            echo "Checkout to v5 branch"
            git checkout v5
            create_or_checkout_branch "${CURRENT_BRANCH}-v5"

            echo "Create and push -v6 branch"
            echo "Checkout to v6 branch"
            git checkout v6
            create_or_checkout_branch "${CURRENT_BRANCH}-v6"     
      - persist_to_workspace:
          # Persist the previous steps to the workspace.
          root: ~/repo
          paths: 
            - current_branch.txt  # Persist the file with the CURRENT_BRANCH variable

  copy-to-v5-branch:
    <<: *defaults
    steps:
      - attach_workspace:
        # Attach to the created workspace.
          at: ~/repo
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:zvnLkEEwEXtFhURIUaOfuiwK71PxzXr79w9CIogoEew"
      - run:
          name: "Copy changes to a v5 and v6 branch"
          command: |
            # Make Current branch var availble in this job
            source current_branch.txt
            echo $CURRENT_BRANCH
            git checkout $CURRENT_BRANCH

            # Path to the file containing the list of SHAs
            git log main..$CURRENT_BRANCH --pretty=format:"%H" > shas.txt
            echo "Added all commits from ${CURRENT_BRANCH} into file sha.txt"
            SHAS_FILE=shas.txt

            V5_BRANCH="${CURRENT_BRANCH}-v5" 
            echo $V5_BRANCH

            echo "You are currently on the branch"
            git branch | grep -o "* .*"

            git checkout $V5_BRANCH

            echo "You are currently on the branch"
            git branch | grep -o "* .*"

            # Check if the file is empty
            if [ ! -s "${SHAS_FILE}" ]; then
                echo "File is empty"
            else
                echo "File is not empty: $(<shas.txt)"
            fi
            
            # Iterate through each gith shar in the file
            while IFS= read -r sha
            do
                echo "Applying cherry-pick for SHA: $sha"
                git cherry-pick "$sha"
                if [ $? -ne 0 ]; then
                    echo "Error during cherry-picking commit $sha. Aborting cherry-pick."
                    git cherry-pick --abort
                    exit 1
                fi
            done < "$SHAS_FILE"

            echo "All SHAs have been cherry-picked successfully."


workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
      # Run the test job on all branches and tags.
          filters:
            tags:
              only: /^v.*/
      - create-v5-v6-branch:
          requires:
            - test
          filters:
            branches:
              only:
                - /^(webg|WEBG)(?!.*-v\d+$).*/
      - copy-to-v5-branch:
          requires:
            - create-v5-v6-branch
          filters:
            branches:
              only:
                - /^(webg|WEBG)(?!.*-v\d+$).*/